- alias: Bureau lamp luus uit
  description: ''
  triggers:
    - trigger: sun
      event: sunrise
      offset: 00:20:00
  conditions: []
  actions:
    - action: switch.turn_off
      target:
        entity_id: switch.bureaulamp_luus
  mode: single
