- alias: Ventilator badkamer aan
  description: "Schakel ventilator in bij snelle stijging luchtvochtigheid (douche)"
  triggers:
    - trigger: numeric_state
      entity_id: sensor.badkamer_luchtvochtigheid_verandering
      above: 0.5
  conditions: []
  actions:
    - type: turn_on
      device_id: f144f9445ca97b1480eeb7b06476a8b9
      entity_id: 6d110bf3aad4a4bac28d3b819d53e3b3
      domain: switch
  mode: single
- alias: Ventilator badkamer uit
  description: "Schakel ventilator uit wanneer daling is gestopt na minimaal 10 minuten"
  triggers:
    - trigger: numeric_state
      entity_id: sensor.badkamer_luchtvochtigheid_verandering
      above: -0.1
      for:
        minutes: 10
  conditions: []
  actions:
    - type: turn_off
      device_id: f144f9445ca97b1480eeb7b06476a8b9
      entity_id: 6d110bf3aad4a4bac28d3b819d53e3b3
      domain: switch
  mode: single
