---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    project_root: /home/joris/workspaces/smartworkx/home
  tasks:
    - name: Copy zigbee2mqtt configuration.yaml to remote host
      ansible.builtin.copy:
        src: "{{ project_root }}/apps/zigbee2mqtt/data/configuration.yaml"
        dest: /opt/smartworkx/zigbee2mqtt/data/configuration.yaml
        mode: '0644'

    - name: Copy mosquitto.conf to remote host
      ansible.builtin.copy:
        src: "{{ project_root }}/apps/mosquitto/config/mosquitto.conf"
        dest: /opt/smartworkx/mosquitto/config/mosquitto.conf
        mode: '0644'

    - name: Copy home-assistant config to remote host
      ansible.builtin.copy:
        src: "{{ project_root }}/apps/home-assistant/"
        dest: /opt/smartworkx/home-assistant/config/
        mode: '0644'

    - name: Copy zwave-js-ui conf to remote host
      ansible.builtin.copy:
        src: "{{ project_root }}/apps/zwave-js-ui/config/settings.json"
        dest: /opt/smartworkx/zwave-js-ui/config/settings.json
        mode: '0644'

    - name: Copy docker-compose file to remote host
      ansible.builtin.copy:
        src: "{{ project_root }}/infrastructure/mars/docker-compose.yml"
        dest: /opt/smartworkx/docker-compose.yml
        mode: '0644'

    - name: Deploy smartworkx stack
      community.docker.docker_compose_v2:
        project_src: /opt/smartworkx
        files:
          - docker-compose.yml
        state: present

