---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    project_root: /home/joris/workspaces/smartworkx/home
  roles:
    - ../../ansible/roles/docker-host
  tasks:
    - name: Install kernel extra modules
      apt:
        name: "linux-modules-extra-{{ ansible_kernel }}"
        state: present

    - name: Create udev rule for Z-Wave stick
      ansible.builtin.copy:
        content: 'SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwave"'
        dest: /etc/udev/rules.d/99-zwave.rules
        mode: '0644'
